aravis_camera_node:
  ros__parameters:
    CameraName: "Hikrobot-00DA4157188"
    TopicName: "left_camera/image"
    SharedFile: "/home/percro_drone/timeshare"
    TriggerEnable: true
    ExposureAutoMode: 2
    ExposureTime: 5000
    AutoExposureTimeLower: 100
    AutoExposureTimeUpper: 20000
    AcquisitionTimeoutUs: 100000
    ImageScale: 1.0
    GainAuto: 2
    Gain: 15.0
    Gamma: 0.7
    GammaSelector: 1
    PixelFormat: 0
